"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from typing import Any

import django_stubs_ext
from django.core.exceptions import ImproperlyConfigured
from environs import Env
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Monkeypatching Django, so stubs will work for all generics,
# see: https://github.com/typeddjango/django-stubs
django_stubs_ext.monkeypatch()

env = Env()
env.read_env()

from backend.logging import DJANGO_ENV, LOGGING  # noqa: E402

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY",
    default="django-insecure-y@oe&%+ay#9-@hvkt7azp^6&dnr(^z(onxxjhp@#8t5oyr1upf",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=DJANGO_ENV == "local")

DEFAULT_ALLOWED_HOSTS = [
    "trojanhq.tplinkdns.com",
    ".run.app",
    "localhost",
    "127.0.0.1",
]
DEFAULT_CSRF_TRUSTED_ORIGINS = [
    "https://*.run.app",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

ALLOWED_HOSTS: list[str] = env.list("ALLOWED_HOSTS", default=DEFAULT_ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS: list[str] = env.list(
    "CSRF_TRUSTED_ORIGINS", default=DEFAULT_CSRF_TRUSTED_ORIGINS
)

if DJANGO_ENV == "prod":
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

SITE_ID = env.int("SITE_ID", default=1)

INSTALLED_APPS = [
    # 3rd party apps (unfold must be before django.contrib.admin)
    "unfold.apps.DefaultAppConfig",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "invitations",  # must come after allauth
    "reactivated",
    "django_structlog",
    "health_check",
    "django_bolt",
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.sites",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 1st party apps
    "apps.common",
    "apps.users",
    "apps.schedules",
    "apps.songs",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "apps.common.middleware.ApiCsrfExemptMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_structlog.middlewares.RequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    {
        "BACKEND": "reactivated.backend.JSX",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "apps.common.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csrf",
                "django.template.context_processors.request",
                "django.template.context_processors.static",
            ]
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.dj_db_url(
        "DATABASE_URL", default="sqlite:///" + str(BASE_DIR / "db.sqlite3")
    ),
}

if DJANGO_ENV == "prod":
    DATABASES["default"]["CONN_MAX_AGE"] = 0
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

PUBLIC_ASSET_DIR = BASE_DIR / "public"
STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATIC_ROOT = PUBLIC_ASSET_DIR / "static"
MEDIA_ROOT = PUBLIC_ASSET_DIR / "media"
STATICFILES_DIRS = [BASE_DIR / "static"]

LOCAL_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
LOCAL_STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

STORAGES: dict[str, dict[str, Any]] = {
    "default": {"BACKEND": LOCAL_FILE_STORAGE},
    "staticfiles": {"BACKEND": LOCAL_STATICFILES_STORAGE},
}

SUPABASE_STORAGE_BUCKET = env.str("SUPABASE_STORAGE_BUCKET", default="")

if DJANGO_ENV == "prod" and not SUPABASE_STORAGE_BUCKET:
    raise ImproperlyConfigured("SUPABASE_STORAGE_BUCKET must be set in production.")

if SUPABASE_STORAGE_BUCKET:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": SUPABASE_STORAGE_BUCKET,
            "endpoint_url": env.str("SUPABASE_S3_ENDPOINT"),
            "access_key": env.str("SUPABASE_S3_ACCESS_KEY"),
            "secret_key": env.str("SUPABASE_S3_SECRET_KEY"),
            "region_name": env.str("SUPABASE_S3_REGION", default="us-east-1"),
            "default_acl": None,
            "querystring_auth": False,
        },
    }

if DJANGO_ENV == "prod":
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "/schedule/"
LOGOUT_REDIRECT_URL = "/"

ACCOUNT_LOGIN_METHODS = ["email"]
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_USER_MODEL_USERNAME_FIELD: str | None = None

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env.str("GOOGLE_CLIENT_ID", ""),
            "secret": env.str("GOOGLE_CLIENT_SECRET", ""),
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "EMAIL_AUTHENTICATION": True
    },
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

ACCOUNT_ADAPTER = "invitations.models.InvitationsAdapter"

INVITATIONS_ADAPTER = ACCOUNT_ADAPTER
INVITATIONS_INVITATION_EXPIRY = 7
INVITATIONS_INVITATION_ONLY = True
INVITATIONS_CONFIRM_INVITE_ON_GET = True
INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = True
INVITATIONS_SIGNUP_REDIRECT = "account_signup"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env.str("EMAIL_HOST", "")
EMAIL_PORT = env.int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", "Worship Prep <noreply@example.com>")

BOLT_PROCESSES = env.int("BOLT_PROCESSES", default=1)

# Unfold Admin Configuration
UNFOLD = {
    "SITE_TITLE": "Worship Prep Admin",
    "SITE_HEADER": "Worship Prep Platform",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/rccgcm_logo.png",
        "dark": lambda request: "/static/rccgcm_logo.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/rccgcm_logo.png",
        "dark": lambda request: "/static/rccgcm_logo.png",
    },
    "SITE_FAVICONS": [
        {
            "rel": "apple-touch-icon",
            "sizes": "180x180",
            "href": lambda request: "/static/apple-touch-icon.png",
        },
        {
            "rel": "icon",
            "type": "image/png",
            "sizes": "32x32",
            "href": lambda request: "/static/favicon-32x32.png",
        },
        {
            "rel": "icon",
            "type": "image/png",
            "sizes": "16x16",
            "href": lambda request: "/static/favicon-16x16.png",
        },
        {
            "rel": "shortcut icon",
            "href": lambda request: "/static/favicon.ico",
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Worship Planning"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Service Schedules"),
                        "icon": "calendar_today",
                        "link": reverse_lazy("admin:schedules_serviceschedule_changelist"),
                    },
                    {
                        "title": _("Templates"),
                        "icon": "description",
                        "link": reverse_lazy("admin:schedules_scheduletemplate_changelist"),
                    },
                    {
                        "title": _("Submissions"),
                        "icon": "inbox",
                        "link": reverse_lazy("admin:schedules_contentsubmission_changelist"),
                    },
                    {
                        "title": _("Contacts"),
                        "icon": "contacts",
                        "link": reverse_lazy("admin:schedules_contact_changelist"),
                    },
                    {
                        "title": _("Songs"),
                        "icon": "music_note",
                        "link": reverse_lazy("admin:songs_song_changelist"),
                    },
                ],
            },
            {
                "title": _("User Management"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "person",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": _("Invitations"),
                        "icon": "mail",
                        "link": reverse_lazy("admin:invitations_invitation_changelist"),
                    },
                    {
                        "title": _("Invitation Requests"),
                        "icon": "mark_email_unread",
                        "link": reverse_lazy("admin:users_invitationrequest_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Sites"),
                        "icon": "language",
                        "link": reverse_lazy("admin:sites_site_changelist"),
                    },
                    {
                        "title": _("Social Accounts"),
                        "icon": "share",
                        "link": reverse_lazy("admin:socialaccount_socialaccount_changelist"),
                    },
                    {
                        "title": _("Social Applications"),
                        "icon": "settings_applications",
                        "link": reverse_lazy("admin:socialaccount_socialapp_changelist"),
                    },
                    {
                        "title": _("Email Addresses"),
                        "icon": "email",
                        "link": reverse_lazy("admin:account_emailaddress_changelist"),
                    },
                ],
            },
        ],
    },
}
