# Generated by Django 5.2.8 on 2026-08-01 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.common.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', apps.common.db.fields.AutoDateTimeField(default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('key_prefix', models.CharField(editable=False, max_length=32, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('revoked_on', models.DateTimeField(blank=True, null=True)),
                ('last_used_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_api_keys', to='api_keys.integrationapikey')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
    ]
