# Generated by Django 5.2.8 on 2026-08-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_keys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationApiKeyRateWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(max_length=32)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_windows",
                        to="api_keys.integrationapikey",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("api_key", "bucket"),
                        name="api_key_unique_rate_bucket",
                    )
                ],
            },
        ),
    ]
