# Generated by Django 5.2.8 on 2026-03-15 06:23

import apps.common.db.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedules", "0003_alter_scheduleitem_item_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("raw_lyrics", models.TextField(blank=True)),
                ("formatted_lyrics", models.TextField(blank=True)),
                ("lyrics_file", models.FileField(blank=True, upload_to="songs/")),
                ("slide_count", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
            },
        ),
        migrations.CreateModel(
            name="SongAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_assignments",
                        to="schedules.scheduleitem",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="songs.song",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song Assignment",
                "verbose_name_plural": "Song Assignments",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule_item", "song"), name="unique_song_per_item"
                    ),
                    models.UniqueConstraint(
                        fields=("schedule_item", "position"),
                        name="unique_song_position",
                    ),
                ],
            },
        ),
    ]
