# Generated by Django 5.2.8 on 2026-08-01 14:06

import apps.catalog.storage
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportRun',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('exporter_instance_id', models.UUIDField()),
                ('contract_version', models.CharField(max_length=64)),
                ('exporter_version', models.CharField(max_length=128)),
                ('parser_version', models.CharField(max_length=128)),
                ('source_fingerprint', models.CharField(max_length=71)),
                ('package_sha256', models.CharField(max_length=71)),
                ('records_fingerprint', models.CharField(max_length=71)),
                ('package_file', models.FileField(storage=apps.catalog.storage.catalog_import_storage, upload_to='packages/%Y/%m/%d')),
                ('report_file', models.FileField(blank=True, storage=apps.catalog.storage.catalog_import_storage, upload_to='reports/%Y/%m/%d')),
                ('status', models.CharField(choices=[('received', 'Received'), ('validating', 'Validating'), ('staging', 'Staging'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('song_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_summary', models.TextField(blank=True)),
                ('exporter_created_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('previous_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_imports', to='catalog.catalogimportrun')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('exporter', 'Exporter'), ('importer', 'Importer')], max_length=16)),
                ('event', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('import_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalog.catalogimportrun')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('completed', 'Completed')], default='candidate', max_length=16)),
                ('staged_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('import_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='catalog.catalogimportrun')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_reference', models.UUIDField(editable=False)),
                ('previous_snapshot_reference', models.UUIDField(editable=False, null=True)),
                ('reason', models.CharField(choices=[('import', 'Import'), ('rollback', 'Rollback')], max_length=16)),
                ('activated_at', models.DateTimeField()),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseding_activations', to='catalog.catalogsnapshot')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogsnapshot')),
            ],
            options={
                'ordering': ['-activated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CatalogState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.catalogsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_uid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('copyright_notice', models.TextField(blank=True)),
                ('cleaned_lyrics', models.TextField(blank=True)),
                ('sections', models.JSONField(default=list)),
                ('slide_count', models.PositiveIntegerField(default=0)),
                ('rights_status', models.CharField(choices=[('approved', 'Approved'), ('unknown', 'Unknown'), ('restricted', 'Restricted')], default='unknown', max_length=16)),
                ('fingerprint_version', models.CharField(max_length=64)),
                ('semantic_fingerprint', models.CharField(max_length=71)),
                ('metadata_fingerprint', models.CharField(max_length=71)),
                ('lyrics_fingerprint', models.CharField(max_length=71)),
                ('structure_fingerprint', models.CharField(max_length=71)),
                ('presentation_fingerprint', models.CharField(max_length=71)),
                ('content_changed_at', models.DateTimeField()),
                ('title_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('lyrics_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='catalog.catalogsnapshot')),
            ],
            options={
                'ordering': ['title', 'song_uid'],
                'indexes': [models.Index(fields=['song_uid'], name='catalog_cat_song_ui_a740b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'song_uid'), name='catalog_unique_song_per_snapshot')],
            },
        ),
    ]
