# Generated by Django 5.2.8 on 2026-02-15 16:41

import apps.common.db.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Schedule Template",
                "verbose_name_plural": "Schedule Templates",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("minister", "Minister"),
                            ("choir", "Choir"),
                            ("pastor", "Pastor"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "phone"), name="unique_contact_name_phone"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("ready", "Ready"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="schedules.scheduletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Schedule",
                "verbose_name_plural": "Service Schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("opening_prayer", "Opening Prayer"),
                            ("worship_song", "Worship Song"),
                            ("hymn", "Hymn"),
                            ("scripture_reading", "Scripture Reading"),
                            ("sermon", "Sermon"),
                            ("announcements", "Announcements"),
                            ("offering", "Offering"),
                            ("special_item", "Special Item"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_items",
                        to="schedules.contact",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="schedules.serviceschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schedule Item",
                "verbose_name_plural": "Schedule Items",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ContentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp"), ("email", "Email")],
                        max_length=20,
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "sender_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("sender_name", models.CharField(max_length=255)),
                (
                    "source_message_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("raw_content", models.TextField()),
                (
                    "parsed_content_type",
                    models.CharField(
                        choices=[
                            ("agenda", "Agenda"),
                            ("lyrics", "Lyrics"),
                            ("scripture", "Scripture"),
                            ("hymn", "Hymn"),
                            ("sermon", "Sermon"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "parsed_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("parsed_body", models.TextField()),
                ("parsed_payload", models.JSONField(blank=True, default=dict)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="schedules.scheduleitem",
                    ),
                ),
                (
                    "created_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="schedules.serviceschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Submission",
                "verbose_name_plural": "Content Submissions",
            },
        ),
        migrations.CreateModel(
            name="TemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_on",
                    apps.common.db.fields.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("deleted_on", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("opening_prayer", "Opening Prayer"),
                            ("worship_song", "Worship Song"),
                            ("hymn", "Hymn"),
                            ("scripture_reading", "Scripture Reading"),
                            ("sermon", "Sermon"),
                            ("announcements", "Announcements"),
                            ("offering", "Offering"),
                            ("special_item", "Special Item"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "default_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_items",
                        to="schedules.contact",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="schedules.scheduletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Item",
                "verbose_name_plural": "Template Items",
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="scheduleitem",
            constraint=models.UniqueConstraint(
                fields=("schedule", "position"), name="unique_schedule_item_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="templateitem",
            constraint=models.UniqueConstraint(
                fields=("template", "position"), name="unique_template_item_position"
            ),
        ),
    ]
