# Generated by Django 5.2.8 on 2026-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_scheduleitem_unique_schedule_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("sunday_school", "Sunday School"),
                    ("opening_prayer", "Opening Prayer"),
                    ("closing_prayer", "Closing Prayer"),
                    ("worship_song", "Worship Song"),
                    ("hymn", "Hymn"),
                    ("scripture_reading", "Scripture Reading"),
                    ("sermon", "Sermon"),
                    ("announcements", "Announcements"),
                    ("offering", "Offering"),
                    ("special_item", "Special Item"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("sunday_school", "Sunday School"),
                    ("opening_prayer", "Opening Prayer"),
                    ("closing_prayer", "Closing Prayer"),
                    ("worship_song", "Worship Song"),
                    ("hymn", "Hymn"),
                    ("scripture_reading", "Scripture Reading"),
                    ("sermon", "Sermon"),
                    ("announcements", "Announcements"),
                    ("offering", "Offering"),
                    ("special_item", "Special Item"),
                ],
                max_length=32,
            ),
        ),
    ]
