# Generated by Django 5.2.8 on 2026-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_alter_scheduleitem_item_type_and_more"),
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleitem",
            name="songs",
            field=models.ManyToManyField(
                blank=True,
                related_name="schedule_items",
                through="songs.SongAssignment",
                to="songs.song",
            ),
        ),
        migrations.AlterField(
            model_name="contentsubmission",
            name="source",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
    ]
