# Generated by Django 5.2.8 on 2026-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_scheduleitem_songs_alter_contentsubmission_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentsubmission",
            name="matched_item",
        ),
    ]
